# YAML EXPLANATION FILE #

Name: Mr.Holmes
Languages: Python,Shell-script,Javascript,Php,Css,Powershell,Batch,C++,Java
Python-Version: Python 3 
Original Creator: Hanan Asif
Author: Hanan Asif
Copyright: (C) Hanan Asif
Copyright-Years: 2021,2022,2023,2024
Project-site: https://lucksi.github.io/Mr.Holmes
Download: git clone https://github.com/thehananasif/Mr.Holmes-by-Hanan-Asif
Platforms: Linux/MacOS/Termux/Windows
Version: T.G.D-1.0.4
License: GNU General Public License v3.0
